# Generated by Django 4.2.7 on 2023-11-30 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='products')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='menu', to='category.category')),
                ('favorite_users', models.ManyToManyField(related_name='favorite_products', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
